"""
Unified data models shared across all components.
"""
import time
from dataclasses import dataclass, field, asdict
from typing import Optional


class OrderState:
    """Order lifecycle states (normalised across all gateways)."""
    PENDING_SUBMIT = "pending_submit"  # Created locally, not yet ACKed by exchange
    OPEN           = "open"            # Resting in the exchange book
    PARTIAL        = "partial"         # Partially filled, still open
    FILLED         = "filled"          # Fully filled
    CANCELLED      = "cancelled"       # Cancelled (may carry partial fills)
    REJECTED       = "rejected"        # Rejected by exchange or risk
    EXPIRED        = "expired"         # Expired (IOC/FOK/GTD)

    TERMINAL = frozenset({FILLED, CANCELLED, REJECTED, EXPIRED})


@dataclass
class OrderUpdate:
    """
    Unified order lifecycle + fill event model.

    One instance covers the full lifecycle: from local creation through exchange
    acknowledgement, incremental fills, and terminal states.

    When ``fill_id`` is non-empty this update also carries a fill event (the
    per-fill fields are populated).  An update without a fill_id is a pure
    state change (e.g. cancel confirmation, open acknowledgement).
    """

    # ── Identity ──────────────────────────────────────────────────────────
    client_order_id: str = ""   # clOrdId — generated by us, sent to exchange
    order_id: str       = ""    # ordId   — assigned by exchange after submission
    gateway: str        = ""    # "okx" | "futu" | "webull"
    strategy: str       = ""    # strategy name; "" for manual/dashboard orders

    # ── Instrument ────────────────────────────────────────────────────────
    symbol: str = ""

    # ── Order params (immutable after submission) ─────────────────────────
    side: str       = ""        # "buy" | "sell"
    order_type: str = "limit"   # "limit" | "market" | "post_only" | "fok" | "ioc"
    price: float    = 0.0       # original limit price (0 for market orders)
    quantity: float = 0.0       # original order quantity

    # ── Lifecycle state ───────────────────────────────────────────────────
    state: str = OrderState.PENDING_SUBMIT  # see OrderState constants

    # ── Cumulative fill tracking ──────────────────────────────────────────
    filled_qty:     float = 0.0   # accFillSz — running total filled quantity
    avg_fill_price: float = 0.0   # avgPx     — VWAP of all fills so far

    # ── Per-fill info (populated only when fill_id is non-empty) ──────────
    fill_id:      str   = ""    # fillId / tradeId — unique per execution
    fill_price:   float = 0.0   # execution price of this fill
    fill_qty:     float = 0.0   # quantity executed in this fill
    fill_fee:     float = 0.0   # fee for this fill (negative = cost, positive = rebate)
    fill_fee_ccy: str   = ""    # fee currency e.g. "USDT", "BTC"
    fill_pnl:     float = 0.0   # realised PnL from this fill (reduce-only legs)
    fill_time_ms: int   = 0     # fill timestamp in milliseconds

    # ── Timestamps ────────────────────────────────────────────────────────
    create_time_ms: int = 0     # order creation time (exchange cTime)
    update_time_ms: int = 0     # last state change time (exchange uTime)

    # ── Metadata ──────────────────────────────────────────────────────────
    update_source: str = "ws"   # "ws" | "rest" | "risk" — origin of this update
    reject_reason: str = ""     # populated when state == REJECTED

    # ── Derived helpers ───────────────────────────────────────────────────
    @property
    def is_fill(self) -> bool:
        """True when this update carries an individual fill event."""
        return bool(self.fill_id)

    @property
    def is_terminal(self) -> bool:
        """True when no further updates are expected for this order."""
        return self.state in OrderState.TERMINAL

    @property
    def remaining_qty(self) -> float:
        return max(0.0, self.quantity - self.filled_qty)

    def to_redis_dict(self) -> dict:
        """Flat string dict suitable for Redis XADD / HSET."""
        return {k: str(v) for k, v in asdict(self).items()}

    @classmethod
    def from_redis_dict(cls, d: dict) -> "OrderUpdate":
        """Reconstruct from a flat Redis dict (all values are strings)."""
        def _coerce(key: str, val: str):
            float_fields = {
                "price", "quantity", "filled_qty", "avg_fill_price",
                "fill_price", "fill_qty", "fill_fee", "fill_pnl",
            }
            int_fields = {"fill_time_ms", "create_time_ms", "update_time_ms"}
            if key in float_fields:
                return float(val or 0)
            if key in int_fields:
                return int(val or 0)
            return val
        return cls(**{k: _coerce(k, v) for k, v in d.items()
                      if k in cls.__dataclass_fields__})


@dataclass
class Order:
    """Intent model — what we want to send to an exchange."""
    order_id: str = ""
    client_order_id: str = ""
    strategy: str = ""
    gateway: str = ""
    symbol: str = ""
    side: str = ""
    order_type: str = "limit"
    price: float = 0.0
    quantity: float = 0.0
    filled_quantity: float = 0.0
    status: str = "pending"  # pending, submitted, partial, filled, cancelled, rejected
    create_time: float = 0.0
    update_time: float = 0.0


@dataclass
class Position:
    gateway: str = ""
    symbol: str = ""
    strategy: str = ""
    side: str = ""  # long, short, flat
    quantity: float = 0.0
    avg_price: float = 0.0
    market_price: float = 0.0
    unrealized_pnl: float = 0.0
    realized_pnl: float = 0.0


@dataclass
class Account:
    gateway: str = ""
    balance: float = 0.0
    available: float = 0.0
    margin_used: float = 0.0
    unrealized_pnl: float = 0.0


@dataclass
class RiskLimits:
    """Per-strategy risk configuration."""
    max_position_size: float = 0.0
    max_notional: float = 0.0
    max_daily_loss: float = 0.0
    max_daily_loss_pct: float = 0.0
    max_delta: float = 0.0
    max_order_rate: int = 100  # orders per minute
    max_drawdown_pct: float = 0.0


@dataclass
class SymbolPosition:
    """
    Single-symbol position tracker using VWAP cost basis.

    PnL accounting
    ──────────────
    realized_pnl   Gross PnL from closed portions, minus fees already deducted.
    unrealized_pnl Mark-to-market on the open position:
                       (last_price − avg_entry) × net_qty
    total_pnl      realized_pnl + unrealized_pnl
    total_fees     Running sum of all fees paid (already deducted from realized_pnl).

    Delta
    ─────
    net_qty        Signed quantity: positive = long, negative = short.
    dollar_delta   net_qty × last_price  (uses avg_entry as fallback before first tick).
    """

    symbol: str
    gateway: str = ""
    strategy: str = ""

    # ── Position state ──────────────────────────────────────────────────────
    net_qty: float         = 0.0   # positive = long, negative = short
    avg_entry_price: float = 0.0   # VWAP of the current open position

    # ── PnL ─────────────────────────────────────────────────────────────────
    realized_pnl: float = 0.0     # net of fees, from fully/partially closed lots
    total_fees: float   = 0.0     # cumulative fees paid (informational only)

    # ── Mark to market ───────────────────────────────────────────────────────
    last_price: float   = 0.0
    last_update_ms: int = 0

    # ── Derived properties ───────────────────────────────────────────────────

    @property
    def unrealized_pnl(self) -> float:
        if self.net_qty == 0 or self.last_price == 0 or self.avg_entry_price == 0:
            return 0.0
        return (self.last_price - self.avg_entry_price) * self.net_qty

    @property
    def dollar_delta(self) -> float:
        """Net USD-equivalent directional exposure."""
        mark = self.last_price or self.avg_entry_price
        return self.net_qty * mark

    @property
    def total_pnl(self) -> float:
        return self.realized_pnl + self.unrealized_pnl

    # ── Fill application ─────────────────────────────────────────────────────

    def apply_fill(self, side: str, fill_qty: float, fill_price: float,
                   fee: float = 0.0) -> None:
        """
        Update position on a new fill.

        VWAP rules
        ──────────
        Adding to position   → update avg_entry_price (VWAP blend)
        Reducing position    → realise PnL on closed qty; avg_entry unchanged
        Crossing zero (flip) → realise PnL on old position; new position
                               opens at fill_price
        """
        if fill_qty <= 0 or fill_price <= 0:
            return

        signed  = fill_qty if side == "buy" else -fill_qty
        old_qty = self.net_qty
        new_qty = old_qty + signed

        if old_qty == 0:
            # Opening from flat
            self.avg_entry_price = fill_price

        elif (old_qty > 0) == (signed > 0):
            # Adding in same direction: VWAP blend
            total_abs = abs(old_qty) + fill_qty
            self.avg_entry_price = (
                abs(old_qty) * self.avg_entry_price + fill_qty * fill_price
            ) / total_abs

        else:
            # Reducing or crossing zero
            close_qty = min(abs(old_qty), fill_qty)

            if old_qty > 0:
                # Closing long: profit when fill_price > avg_entry
                self.realized_pnl += (fill_price - self.avg_entry_price) * close_qty
            else:
                # Closing short: profit when fill_price < avg_entry
                self.realized_pnl += (self.avg_entry_price - fill_price) * close_qty

            if new_qty != 0 and ((old_qty > 0) != (new_qty > 0)):
                # Crossed zero: new position opens at this fill_price
                self.avg_entry_price = fill_price
            elif new_qty == 0:
                self.avg_entry_price = 0.0
            # else: partial close — avg_entry unchanged for remaining qty

        self.net_qty = new_qty

        # Fees reduce realized PnL; tracked separately for reporting
        self.realized_pnl -= abs(fee)
        self.total_fees   += abs(fee)
        self.last_update_ms = int(time.time() * 1000)

    # ── Serialisation ────────────────────────────────────────────────────────

    def to_dict(self) -> dict:
        return {
            "symbol":          self.symbol,
            "gateway":         self.gateway,
            "strategy":        self.strategy,
            "net_qty":         self.net_qty,
            "avg_entry_price": round(self.avg_entry_price, 8),
            "realized_pnl":    round(self.realized_pnl, 8),
            "unrealized_pnl":  round(self.unrealized_pnl, 8),
            "total_pnl":       round(self.total_pnl, 8),
            "total_fees":      round(self.total_fees, 8),
            "dollar_delta":    round(self.dollar_delta, 2),
            "last_price":      self.last_price,
            "last_update_ms":  self.last_update_ms,
        }
